/**
 * The <unnamed> factory builder project.
 *
 * @file /src/engine/transportation/TransportationTile.h
 *
 * @brief Describe a tile where a Transporter object is allowed to pass by.
 */

/*
 * CHANGELOG:
 * 17/12/2020: File creation (NG)
 */

#ifndef FACTORYBUILDER_TRANSPORTATIONTILE_H
#define FACTORYBUILDER_TRANSPORTATIONTILE_H

#include <IEdge.h>

class TransportationTile : public IEdge
{
public:

    /**
     * \brief The Transportation constructor
     * \param _uuid The IGraphElement UUID (generated by the GraphElementFactory)
     * \param _size The IEdge FIFO size, in number of elements.
     */
    TransportationTile(s_GraphElementUUID _uuid, s_EdgeFifoSize _size);
    ~TransportationTile();

    /**
     * Request a Transporter. This function overrides the IEdge one, as it ensures the Transporter is ready to be released.
     * @return
     */
    IToken *getToken();

};

#endif //FACTORYBUILDER_TRANSPORTATIONTILE_H
